services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=catgram
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres:
