services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=catgram
      - POSTGRES_PASSWORD=changeme
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
  
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres:
